schema = 3

[mod]
  [mod.'github.com/unmango/go']
    version = 'v0.15.1'
    hash = 'sha256-iaw6AuhEYu7LdLQnOL6Zmu9kp41nRwaz+lpeZ5ihRww='

  [mod.'github.com/unstoppablemango/ihfs']
    version = 'v0.0.0-20260301044319-5c1c6e196ed6'
    hash = 'sha256-f8pqtx81ldjZviv2uUNe5AW+sgQPFdoCCd9viZBcKYQ='

  [mod.'go.uber.org/mock']
    version = 'v0.5.0'
    hash = 'sha256-OLgbIRFUgt2taXypu5zSfnUZeeevNaU/myCdXBOBVaA='

  [mod.'golang.org/x/mod']
    version = 'v0.32.0'
    hash = 'sha256-4gbgIqTOo0vcYV3l4MIwmT/h8H9PXmcfrJ3z4B26Zl0='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/tools']
    version = 'v0.41.0'
    hash = 'sha256-/Plnksa1jSr4jYJc2oCH9fcjGbWocM7EYposMP0tScQ='
