schema = 3

[mod]
  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/nix-community/go-nix']
    version = 'v0.0.0-20250101154619-4bdde671e0a1'
    hash = 'sha256-8mewNCfdfhZtkckVxxJA3aNS7mGZEwg6xXymEq8g1wY='

  [mod.'github.com/nix-community/gomod2nix']
    version = 'v1.7.1-0.20260208211840-1201ddd1279c'
    hash = 'sha256-4xaGklmIGzlDFWThIU+w+0sJW3lO0to98vOWbnblAmA='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.2.4'
    hash = 'sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q='

  [mod.'github.com/sirupsen/logrus']
    version = 'v1.9.4'
    hash = 'sha256-ltRvmtM3XTCAFwY0IesfRqYIivyXPPuvkFjL4ARh1wg='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/unmango/go']
    version = 'v0.15.1'
    hash = 'sha256-iaw6AuhEYu7LdLQnOL6Zmu9kp41nRwaz+lpeZ5ihRww='

  [mod.'github.com/unstoppablemango/ihfs']
    version = 'v0.0.1'
    hash = 'sha256-R38Gnl5xzWnIJN3GmL50HblOO/avd120OKYZo5/j7N0='

  [mod.'go.uber.org/mock']
    version = 'v0.6.0'
    hash = 'sha256-m11cxIbrvOowa6xj11AztzfFk86DwR6SNO1lStcKzvo='

  [mod.'golang.org/x/mod']
    version = 'v0.33.0'
    hash = 'sha256-NR+ZSeQKbfVP4Cu/SlNIivMa+c1OMyOSMxLSjX+LZJI='

  [mod.'golang.org/x/sync']
    version = 'v0.19.0'
    hash = 'sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno='

  [mod.'golang.org/x/sys']
    version = 'v0.41.0'
    hash = 'sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk='

  [mod.'golang.org/x/tools']
    version = 'v0.42.0'
    hash = 'sha256-JTwzoJeqCW5aphjQR0SItRGov7dKVbFk3a4V2U2+vd4='

  [mod.'golang.org/x/tools/go/vcs']
    version = 'v0.1.0-deprecated'
    hash = 'sha256-57YB10tiRsVSRvJqKYST+iON6yZYGL7eRSzrFcImC8Y='
