// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unstoppablemango/ihfs (interfaces: ChmodFS,ChownFS,ChtimesFS,CopyFS,CreateFS,CreateTempFS,GlobFS,LinkerFS,MkdirFS,MkdirAllFS,MkdirTempFS,OpenFileFS,OsFS,ReadDirFS,ReadDirNamesFS,ReadFileFS,ReadLinkFS,RemoveFS,RemoveAllFS,RenameFS,StatFS,SubFS,SymlinkFS,TempFileFS,WriteFileFS)
//
// Generated by this command:
//
//	mockgen -destination=mock_fs.go -package=mockfs github.com/unstoppablemango/ihfs ChmodFS,ChownFS,ChtimesFS,CopyFS,CreateFS,CreateTempFS,GlobFS,LinkerFS,MkdirFS,MkdirAllFS,MkdirTempFS,OpenFileFS,OsFS,ReadDirFS,ReadDirNamesFS,ReadFileFS,ReadLinkFS,RemoveFS,RemoveAllFS,RenameFS,StatFS,SubFS,SymlinkFS,TempFileFS,WriteFileFS
//

// Package mockfs is a generated GoMock package.
package mockfs

import (
	fs "io/fs"
	reflect "reflect"
	time "time"

	os "github.com/unmango/go/os"
	ihfs "github.com/unstoppablemango/ihfs"
	gomock "go.uber.org/mock/gomock"
)

// MockChmodFS is a mock of ChmodFS interface.
type MockChmodFS struct {
	ctrl     *gomock.Controller
	recorder *MockChmodFSMockRecorder
	isgomock struct{}
}

// MockChmodFSMockRecorder is the mock recorder for MockChmodFS.
type MockChmodFSMockRecorder struct {
	mock *MockChmodFS
}

// NewMockChmodFS creates a new mock instance.
func NewMockChmodFS(ctrl *gomock.Controller) *MockChmodFS {
	mock := &MockChmodFS{ctrl: ctrl}
	mock.recorder = &MockChmodFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChmodFS) EXPECT() *MockChmodFSMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *MockChmodFS) Chmod(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MockChmodFSMockRecorder) Chmod(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MockChmodFS)(nil).Chmod), name, mode)
}

// Open mocks base method.
func (m *MockChmodFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockChmodFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockChmodFS)(nil).Open), name)
}

// MockChownFS is a mock of ChownFS interface.
type MockChownFS struct {
	ctrl     *gomock.Controller
	recorder *MockChownFSMockRecorder
	isgomock struct{}
}

// MockChownFSMockRecorder is the mock recorder for MockChownFS.
type MockChownFSMockRecorder struct {
	mock *MockChownFS
}

// NewMockChownFS creates a new mock instance.
func NewMockChownFS(ctrl *gomock.Controller) *MockChownFS {
	mock := &MockChownFS{ctrl: ctrl}
	mock.recorder = &MockChownFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChownFS) EXPECT() *MockChownFSMockRecorder {
	return m.recorder
}

// Chown mocks base method.
func (m *MockChownFS) Chown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *MockChownFSMockRecorder) Chown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*MockChownFS)(nil).Chown), name, uid, gid)
}

// Open mocks base method.
func (m *MockChownFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockChownFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockChownFS)(nil).Open), name)
}

// MockChtimesFS is a mock of ChtimesFS interface.
type MockChtimesFS struct {
	ctrl     *gomock.Controller
	recorder *MockChtimesFSMockRecorder
	isgomock struct{}
}

// MockChtimesFSMockRecorder is the mock recorder for MockChtimesFS.
type MockChtimesFSMockRecorder struct {
	mock *MockChtimesFS
}

// NewMockChtimesFS creates a new mock instance.
func NewMockChtimesFS(ctrl *gomock.Controller) *MockChtimesFS {
	mock := &MockChtimesFS{ctrl: ctrl}
	mock.recorder = &MockChtimesFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChtimesFS) EXPECT() *MockChtimesFSMockRecorder {
	return m.recorder
}

// Chtimes mocks base method.
func (m *MockChtimesFS) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *MockChtimesFSMockRecorder) Chtimes(name, atime, mtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*MockChtimesFS)(nil).Chtimes), name, atime, mtime)
}

// Open mocks base method.
func (m *MockChtimesFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockChtimesFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockChtimesFS)(nil).Open), name)
}

// MockCopyFS is a mock of CopyFS interface.
type MockCopyFS struct {
	ctrl     *gomock.Controller
	recorder *MockCopyFSMockRecorder
	isgomock struct{}
}

// MockCopyFSMockRecorder is the mock recorder for MockCopyFS.
type MockCopyFSMockRecorder struct {
	mock *MockCopyFS
}

// NewMockCopyFS creates a new mock instance.
func NewMockCopyFS(ctrl *gomock.Controller) *MockCopyFS {
	mock := &MockCopyFS{ctrl: ctrl}
	mock.recorder = &MockCopyFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCopyFS) EXPECT() *MockCopyFSMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockCopyFS) Copy(dir string, fsys ihfs.FS) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", dir, fsys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockCopyFSMockRecorder) Copy(dir, fsys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockCopyFS)(nil).Copy), dir, fsys)
}

// Open mocks base method.
func (m *MockCopyFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCopyFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCopyFS)(nil).Open), name)
}

// MockCreateFS is a mock of CreateFS interface.
type MockCreateFS struct {
	ctrl     *gomock.Controller
	recorder *MockCreateFSMockRecorder
	isgomock struct{}
}

// MockCreateFSMockRecorder is the mock recorder for MockCreateFS.
type MockCreateFSMockRecorder struct {
	mock *MockCreateFS
}

// NewMockCreateFS creates a new mock instance.
func NewMockCreateFS(ctrl *gomock.Controller) *MockCreateFS {
	mock := &MockCreateFS{ctrl: ctrl}
	mock.recorder = &MockCreateFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateFS) EXPECT() *MockCreateFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateFS) Create(name string) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateFSMockRecorder) Create(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateFS)(nil).Create), name)
}

// Open mocks base method.
func (m *MockCreateFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCreateFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCreateFS)(nil).Open), name)
}

// MockCreateTempFS is a mock of CreateTempFS interface.
type MockCreateTempFS struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTempFSMockRecorder
	isgomock struct{}
}

// MockCreateTempFSMockRecorder is the mock recorder for MockCreateTempFS.
type MockCreateTempFSMockRecorder struct {
	mock *MockCreateTempFS
}

// NewMockCreateTempFS creates a new mock instance.
func NewMockCreateTempFS(ctrl *gomock.Controller) *MockCreateTempFS {
	mock := &MockCreateTempFS{ctrl: ctrl}
	mock.recorder = &MockCreateTempFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTempFS) EXPECT() *MockCreateTempFSMockRecorder {
	return m.recorder
}

// CreateTemp mocks base method.
func (m *MockCreateTempFS) CreateTemp(dir, pattern string) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemp", dir, pattern)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemp indicates an expected call of CreateTemp.
func (mr *MockCreateTempFSMockRecorder) CreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemp", reflect.TypeOf((*MockCreateTempFS)(nil).CreateTemp), dir, pattern)
}

// Open mocks base method.
func (m *MockCreateTempFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCreateTempFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCreateTempFS)(nil).Open), name)
}

// MockGlobFS is a mock of GlobFS interface.
type MockGlobFS struct {
	ctrl     *gomock.Controller
	recorder *MockGlobFSMockRecorder
	isgomock struct{}
}

// MockGlobFSMockRecorder is the mock recorder for MockGlobFS.
type MockGlobFSMockRecorder struct {
	mock *MockGlobFS
}

// NewMockGlobFS creates a new mock instance.
func NewMockGlobFS(ctrl *gomock.Controller) *MockGlobFS {
	mock := &MockGlobFS{ctrl: ctrl}
	mock.recorder = &MockGlobFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobFS) EXPECT() *MockGlobFSMockRecorder {
	return m.recorder
}

// Glob mocks base method.
func (m *MockGlobFS) Glob(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Glob", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Glob indicates an expected call of Glob.
func (mr *MockGlobFSMockRecorder) Glob(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Glob", reflect.TypeOf((*MockGlobFS)(nil).Glob), pattern)
}

// Open mocks base method.
func (m *MockGlobFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockGlobFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockGlobFS)(nil).Open), name)
}

// MockLinkerFS is a mock of LinkerFS interface.
type MockLinkerFS struct {
	ctrl     *gomock.Controller
	recorder *MockLinkerFSMockRecorder
	isgomock struct{}
}

// MockLinkerFSMockRecorder is the mock recorder for MockLinkerFS.
type MockLinkerFSMockRecorder struct {
	mock *MockLinkerFS
}

// NewMockLinkerFS creates a new mock instance.
func NewMockLinkerFS(ctrl *gomock.Controller) *MockLinkerFS {
	mock := &MockLinkerFS{ctrl: ctrl}
	mock.recorder = &MockLinkerFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkerFS) EXPECT() *MockLinkerFSMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *MockLinkerFS) Lstat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockLinkerFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockLinkerFS)(nil).Lstat), name)
}

// Open mocks base method.
func (m *MockLinkerFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockLinkerFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockLinkerFS)(nil).Open), name)
}

// ReadLink mocks base method.
func (m *MockLinkerFS) ReadLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockLinkerFSMockRecorder) ReadLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockLinkerFS)(nil).ReadLink), name)
}

// Symlink mocks base method.
func (m *MockLinkerFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockLinkerFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockLinkerFS)(nil).Symlink), oldname, newname)
}

// MockMkdirFS is a mock of MkdirFS interface.
type MockMkdirFS struct {
	ctrl     *gomock.Controller
	recorder *MockMkdirFSMockRecorder
	isgomock struct{}
}

// MockMkdirFSMockRecorder is the mock recorder for MockMkdirFS.
type MockMkdirFSMockRecorder struct {
	mock *MockMkdirFS
}

// NewMockMkdirFS creates a new mock instance.
func NewMockMkdirFS(ctrl *gomock.Controller) *MockMkdirFS {
	mock := &MockMkdirFS{ctrl: ctrl}
	mock.recorder = &MockMkdirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMkdirFS) EXPECT() *MockMkdirFSMockRecorder {
	return m.recorder
}

// Mkdir mocks base method.
func (m *MockMkdirFS) Mkdir(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockMkdirFSMockRecorder) Mkdir(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockMkdirFS)(nil).Mkdir), name, mode)
}

// Open mocks base method.
func (m *MockMkdirFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockMkdirFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockMkdirFS)(nil).Open), name)
}

// MockMkdirAllFS is a mock of MkdirAllFS interface.
type MockMkdirAllFS struct {
	ctrl     *gomock.Controller
	recorder *MockMkdirAllFSMockRecorder
	isgomock struct{}
}

// MockMkdirAllFSMockRecorder is the mock recorder for MockMkdirAllFS.
type MockMkdirAllFSMockRecorder struct {
	mock *MockMkdirAllFS
}

// NewMockMkdirAllFS creates a new mock instance.
func NewMockMkdirAllFS(ctrl *gomock.Controller) *MockMkdirAllFS {
	mock := &MockMkdirAllFS{ctrl: ctrl}
	mock.recorder = &MockMkdirAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMkdirAllFS) EXPECT() *MockMkdirAllFSMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MockMkdirAllFS) MkdirAll(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockMkdirAllFSMockRecorder) MkdirAll(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockMkdirAllFS)(nil).MkdirAll), name, mode)
}

// Open mocks base method.
func (m *MockMkdirAllFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockMkdirAllFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockMkdirAllFS)(nil).Open), name)
}

// MockMkdirTempFS is a mock of MkdirTempFS interface.
type MockMkdirTempFS struct {
	ctrl     *gomock.Controller
	recorder *MockMkdirTempFSMockRecorder
	isgomock struct{}
}

// MockMkdirTempFSMockRecorder is the mock recorder for MockMkdirTempFS.
type MockMkdirTempFSMockRecorder struct {
	mock *MockMkdirTempFS
}

// NewMockMkdirTempFS creates a new mock instance.
func NewMockMkdirTempFS(ctrl *gomock.Controller) *MockMkdirTempFS {
	mock := &MockMkdirTempFS{ctrl: ctrl}
	mock.recorder = &MockMkdirTempFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMkdirTempFS) EXPECT() *MockMkdirTempFSMockRecorder {
	return m.recorder
}

// MkdirTemp mocks base method.
func (m *MockMkdirTempFS) MkdirTemp(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirTemp", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MkdirTemp indicates an expected call of MkdirTemp.
func (mr *MockMkdirTempFSMockRecorder) MkdirTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirTemp", reflect.TypeOf((*MockMkdirTempFS)(nil).MkdirTemp), dir, pattern)
}

// Open mocks base method.
func (m *MockMkdirTempFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockMkdirTempFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockMkdirTempFS)(nil).Open), name)
}

// MockOpenFileFS is a mock of OpenFileFS interface.
type MockOpenFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockOpenFileFSMockRecorder
	isgomock struct{}
}

// MockOpenFileFSMockRecorder is the mock recorder for MockOpenFileFS.
type MockOpenFileFSMockRecorder struct {
	mock *MockOpenFileFS
}

// NewMockOpenFileFS creates a new mock instance.
func NewMockOpenFileFS(ctrl *gomock.Controller) *MockOpenFileFS {
	mock := &MockOpenFileFS{ctrl: ctrl}
	mock.recorder = &MockOpenFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenFileFS) EXPECT() *MockOpenFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockOpenFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockOpenFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockOpenFileFS)(nil).Open), name)
}

// OpenFile mocks base method.
func (m *MockOpenFileFS) OpenFile(name string, flag int, perm ihfs.FileMode) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", name, flag, perm)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *MockOpenFileFSMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*MockOpenFileFS)(nil).OpenFile), name, flag, perm)
}

// MockOsFS is a mock of OsFS interface.
type MockOsFS struct {
	ctrl     *gomock.Controller
	recorder *MockOsFSMockRecorder
	isgomock struct{}
}

// MockOsFSMockRecorder is the mock recorder for MockOsFS.
type MockOsFSMockRecorder struct {
	mock *MockOsFS
}

// NewMockOsFS creates a new mock instance.
func NewMockOsFS(ctrl *gomock.Controller) *MockOsFS {
	mock := &MockOsFS{ctrl: ctrl}
	mock.recorder = &MockOsFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOsFS) EXPECT() *MockOsFSMockRecorder {
	return m.recorder
}

// Chdir mocks base method.
func (m *MockOsFS) Chdir(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chdir", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chdir indicates an expected call of Chdir.
func (mr *MockOsFSMockRecorder) Chdir(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chdir", reflect.TypeOf((*MockOsFS)(nil).Chdir), dir)
}

// Chmod mocks base method.
func (m *MockOsFS) Chmod(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *MockOsFSMockRecorder) Chmod(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*MockOsFS)(nil).Chmod), name, mode)
}

// Chown mocks base method.
func (m *MockOsFS) Chown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *MockOsFSMockRecorder) Chown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*MockOsFS)(nil).Chown), name, uid, gid)
}

// Chtimes mocks base method.
func (m *MockOsFS) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *MockOsFSMockRecorder) Chtimes(name, atime, mtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*MockOsFS)(nil).Chtimes), name, atime, mtime)
}

// CopyFS mocks base method.
func (m *MockOsFS) CopyFS(dir string, fsys fs.FS) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFS", dir, fsys)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFS indicates an expected call of CopyFS.
func (mr *MockOsFSMockRecorder) CopyFS(dir, fsys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFS", reflect.TypeOf((*MockOsFS)(nil).CopyFS), dir, fsys)
}

// CreateTemp mocks base method.
func (m *MockOsFS) CreateTemp(dir, pattern string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemp", dir, pattern)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemp indicates an expected call of CreateTemp.
func (mr *MockOsFSMockRecorder) CreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemp", reflect.TypeOf((*MockOsFS)(nil).CreateTemp), dir, pattern)
}

// DirFS mocks base method.
func (m *MockOsFS) DirFS(dir string) fs.FS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirFS", dir)
	ret0, _ := ret[0].(fs.FS)
	return ret0
}

// DirFS indicates an expected call of DirFS.
func (mr *MockOsFSMockRecorder) DirFS(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirFS", reflect.TypeOf((*MockOsFS)(nil).DirFS), dir)
}

// Lchown mocks base method.
func (m *MockOsFS) Lchown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lchown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lchown indicates an expected call of Lchown.
func (mr *MockOsFSMockRecorder) Lchown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lchown", reflect.TypeOf((*MockOsFS)(nil).Lchown), name, uid, gid)
}

// Link mocks base method.
func (m *MockOsFS) Link(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Link", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Link indicates an expected call of Link.
func (mr *MockOsFSMockRecorder) Link(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Link", reflect.TypeOf((*MockOsFS)(nil).Link), oldname, newname)
}

// Lstat mocks base method.
func (m *MockOsFS) Lstat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockOsFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockOsFS)(nil).Lstat), name)
}

// Mkdir mocks base method.
func (m *MockOsFS) Mkdir(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MockOsFSMockRecorder) Mkdir(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MockOsFS)(nil).Mkdir), name, mode)
}

// MkdirAll mocks base method.
func (m *MockOsFS) MkdirAll(path string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockOsFSMockRecorder) MkdirAll(path, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockOsFS)(nil).MkdirAll), path, mode)
}

// MkdirTemp mocks base method.
func (m *MockOsFS) MkdirTemp(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirTemp", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MkdirTemp indicates an expected call of MkdirTemp.
func (mr *MockOsFSMockRecorder) MkdirTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirTemp", reflect.TypeOf((*MockOsFS)(nil).MkdirTemp), dir, pattern)
}

// Open mocks base method.
func (m *MockOsFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockOsFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockOsFS)(nil).Open), name)
}

// OpenInRoot mocks base method.
func (m *MockOsFS) OpenInRoot(dir, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenInRoot", dir, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenInRoot indicates an expected call of OpenInRoot.
func (mr *MockOsFSMockRecorder) OpenInRoot(dir, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenInRoot", reflect.TypeOf((*MockOsFS)(nil).OpenInRoot), dir, name)
}

// OpenRoot mocks base method.
func (m *MockOsFS) OpenRoot(name string) (*os.Root, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenRoot", name)
	ret0, _ := ret[0].(*os.Root)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenRoot indicates an expected call of OpenRoot.
func (mr *MockOsFSMockRecorder) OpenRoot(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenRoot", reflect.TypeOf((*MockOsFS)(nil).OpenRoot), name)
}

// ReadDir mocks base method.
func (m *MockOsFS) ReadDir(name string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockOsFSMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockOsFS)(nil).ReadDir), name)
}

// ReadFile mocks base method.
func (m *MockOsFS) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockOsFSMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockOsFS)(nil).ReadFile), name)
}

// Readlink mocks base method.
func (m *MockOsFS) Readlink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readlink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readlink indicates an expected call of Readlink.
func (mr *MockOsFSMockRecorder) Readlink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readlink", reflect.TypeOf((*MockOsFS)(nil).Readlink), name)
}

// Remove mocks base method.
func (m *MockOsFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockOsFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockOsFS)(nil).Remove), name)
}

// RemoveAll mocks base method.
func (m *MockOsFS) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockOsFSMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockOsFS)(nil).RemoveAll), path)
}

// Rename mocks base method.
func (m *MockOsFS) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockOsFSMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockOsFS)(nil).Rename), oldpath, newpath)
}

// SameFile mocks base method.
func (m *MockOsFS) SameFile(fi1, fi2 os.FileInfo) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameFile", fi1, fi2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameFile indicates an expected call of SameFile.
func (mr *MockOsFSMockRecorder) SameFile(fi1, fi2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameFile", reflect.TypeOf((*MockOsFS)(nil).SameFile), fi1, fi2)
}

// Stat mocks base method.
func (m *MockOsFS) Stat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockOsFSMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockOsFS)(nil).Stat), name)
}

// Symlink mocks base method.
func (m *MockOsFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockOsFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockOsFS)(nil).Symlink), oldname, newname)
}

// Truncate mocks base method.
func (m *MockOsFS) Truncate(name string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", name, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *MockOsFSMockRecorder) Truncate(name, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*MockOsFS)(nil).Truncate), name, size)
}

// WriteFile mocks base method.
func (m *MockOsFS) WriteFile(name string, data []byte, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockOsFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockOsFS)(nil).WriteFile), name, data, perm)
}

// MockReadDirFS is a mock of ReadDirFS interface.
type MockReadDirFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadDirFSMockRecorder
	isgomock struct{}
}

// MockReadDirFSMockRecorder is the mock recorder for MockReadDirFS.
type MockReadDirFSMockRecorder struct {
	mock *MockReadDirFS
}

// NewMockReadDirFS creates a new mock instance.
func NewMockReadDirFS(ctrl *gomock.Controller) *MockReadDirFS {
	mock := &MockReadDirFS{ctrl: ctrl}
	mock.recorder = &MockReadDirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadDirFS) EXPECT() *MockReadDirFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReadDirFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadDirFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadDirFS)(nil).Open), name)
}

// ReadDir mocks base method.
func (m *MockReadDirFS) ReadDir(name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockReadDirFSMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockReadDirFS)(nil).ReadDir), name)
}

// MockReadDirNamesFS is a mock of ReadDirNamesFS interface.
type MockReadDirNamesFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadDirNamesFSMockRecorder
	isgomock struct{}
}

// MockReadDirNamesFSMockRecorder is the mock recorder for MockReadDirNamesFS.
type MockReadDirNamesFSMockRecorder struct {
	mock *MockReadDirNamesFS
}

// NewMockReadDirNamesFS creates a new mock instance.
func NewMockReadDirNamesFS(ctrl *gomock.Controller) *MockReadDirNamesFS {
	mock := &MockReadDirNamesFS{ctrl: ctrl}
	mock.recorder = &MockReadDirNamesFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadDirNamesFS) EXPECT() *MockReadDirNamesFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReadDirNamesFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadDirNamesFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadDirNamesFS)(nil).Open), name)
}

// ReadDirNames mocks base method.
func (m *MockReadDirNamesFS) ReadDirNames(name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDirNames", name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDirNames indicates an expected call of ReadDirNames.
func (mr *MockReadDirNamesFSMockRecorder) ReadDirNames(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDirNames", reflect.TypeOf((*MockReadDirNamesFS)(nil).ReadDirNames), name)
}

// MockReadFileFS is a mock of ReadFileFS interface.
type MockReadFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadFileFSMockRecorder
	isgomock struct{}
}

// MockReadFileFSMockRecorder is the mock recorder for MockReadFileFS.
type MockReadFileFSMockRecorder struct {
	mock *MockReadFileFS
}

// NewMockReadFileFS creates a new mock instance.
func NewMockReadFileFS(ctrl *gomock.Controller) *MockReadFileFS {
	mock := &MockReadFileFS{ctrl: ctrl}
	mock.recorder = &MockReadFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadFileFS) EXPECT() *MockReadFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockReadFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadFileFS)(nil).Open), name)
}

// ReadFile mocks base method.
func (m *MockReadFileFS) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockReadFileFSMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockReadFileFS)(nil).ReadFile), name)
}

// MockReadLinkFS is a mock of ReadLinkFS interface.
type MockReadLinkFS struct {
	ctrl     *gomock.Controller
	recorder *MockReadLinkFSMockRecorder
	isgomock struct{}
}

// MockReadLinkFSMockRecorder is the mock recorder for MockReadLinkFS.
type MockReadLinkFSMockRecorder struct {
	mock *MockReadLinkFS
}

// NewMockReadLinkFS creates a new mock instance.
func NewMockReadLinkFS(ctrl *gomock.Controller) *MockReadLinkFS {
	mock := &MockReadLinkFS{ctrl: ctrl}
	mock.recorder = &MockReadLinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadLinkFS) EXPECT() *MockReadLinkFSMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *MockReadLinkFS) Lstat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockReadLinkFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockReadLinkFS)(nil).Lstat), name)
}

// Open mocks base method.
func (m *MockReadLinkFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockReadLinkFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockReadLinkFS)(nil).Open), name)
}

// ReadLink mocks base method.
func (m *MockReadLinkFS) ReadLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *MockReadLinkFSMockRecorder) ReadLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*MockReadLinkFS)(nil).ReadLink), name)
}

// MockRemoveFS is a mock of RemoveFS interface.
type MockRemoveFS struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveFSMockRecorder
	isgomock struct{}
}

// MockRemoveFSMockRecorder is the mock recorder for MockRemoveFS.
type MockRemoveFSMockRecorder struct {
	mock *MockRemoveFS
}

// NewMockRemoveFS creates a new mock instance.
func NewMockRemoveFS(ctrl *gomock.Controller) *MockRemoveFS {
	mock := &MockRemoveFS{ctrl: ctrl}
	mock.recorder = &MockRemoveFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveFS) EXPECT() *MockRemoveFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockRemoveFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRemoveFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRemoveFS)(nil).Open), name)
}

// Remove mocks base method.
func (m *MockRemoveFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRemoveFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRemoveFS)(nil).Remove), name)
}

// MockRemoveAllFS is a mock of RemoveAllFS interface.
type MockRemoveAllFS struct {
	ctrl     *gomock.Controller
	recorder *MockRemoveAllFSMockRecorder
	isgomock struct{}
}

// MockRemoveAllFSMockRecorder is the mock recorder for MockRemoveAllFS.
type MockRemoveAllFSMockRecorder struct {
	mock *MockRemoveAllFS
}

// NewMockRemoveAllFS creates a new mock instance.
func NewMockRemoveAllFS(ctrl *gomock.Controller) *MockRemoveAllFS {
	mock := &MockRemoveAllFS{ctrl: ctrl}
	mock.recorder = &MockRemoveAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoveAllFS) EXPECT() *MockRemoveAllFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockRemoveAllFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRemoveAllFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRemoveAllFS)(nil).Open), name)
}

// RemoveAll mocks base method.
func (m *MockRemoveAllFS) RemoveAll(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockRemoveAllFSMockRecorder) RemoveAll(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockRemoveAllFS)(nil).RemoveAll), name)
}

// MockRenameFS is a mock of RenameFS interface.
type MockRenameFS struct {
	ctrl     *gomock.Controller
	recorder *MockRenameFSMockRecorder
	isgomock struct{}
}

// MockRenameFSMockRecorder is the mock recorder for MockRenameFS.
type MockRenameFSMockRecorder struct {
	mock *MockRenameFS
}

// NewMockRenameFS creates a new mock instance.
func NewMockRenameFS(ctrl *gomock.Controller) *MockRenameFS {
	mock := &MockRenameFS{ctrl: ctrl}
	mock.recorder = &MockRenameFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenameFS) EXPECT() *MockRenameFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockRenameFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockRenameFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockRenameFS)(nil).Open), name)
}

// Rename mocks base method.
func (m *MockRenameFS) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *MockRenameFSMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockRenameFS)(nil).Rename), oldpath, newpath)
}

// MockStatFS is a mock of StatFS interface.
type MockStatFS struct {
	ctrl     *gomock.Controller
	recorder *MockStatFSMockRecorder
	isgomock struct{}
}

// MockStatFSMockRecorder is the mock recorder for MockStatFS.
type MockStatFSMockRecorder struct {
	mock *MockStatFS
}

// NewMockStatFS creates a new mock instance.
func NewMockStatFS(ctrl *gomock.Controller) *MockStatFS {
	mock := &MockStatFS{ctrl: ctrl}
	mock.recorder = &MockStatFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatFS) EXPECT() *MockStatFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockStatFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockStatFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockStatFS)(nil).Open), name)
}

// Stat mocks base method.
func (m *MockStatFS) Stat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockStatFSMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockStatFS)(nil).Stat), name)
}

// MockSubFS is a mock of SubFS interface.
type MockSubFS struct {
	ctrl     *gomock.Controller
	recorder *MockSubFSMockRecorder
	isgomock struct{}
}

// MockSubFSMockRecorder is the mock recorder for MockSubFS.
type MockSubFSMockRecorder struct {
	mock *MockSubFS
}

// NewMockSubFS creates a new mock instance.
func NewMockSubFS(ctrl *gomock.Controller) *MockSubFS {
	mock := &MockSubFS{ctrl: ctrl}
	mock.recorder = &MockSubFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubFS) EXPECT() *MockSubFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockSubFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockSubFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSubFS)(nil).Open), name)
}

// Sub mocks base method.
func (m *MockSubFS) Sub(dir string) (fs.FS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sub", dir)
	ret0, _ := ret[0].(fs.FS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sub indicates an expected call of Sub.
func (mr *MockSubFSMockRecorder) Sub(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sub", reflect.TypeOf((*MockSubFS)(nil).Sub), dir)
}

// MockSymlinkFS is a mock of SymlinkFS interface.
type MockSymlinkFS struct {
	ctrl     *gomock.Controller
	recorder *MockSymlinkFSMockRecorder
	isgomock struct{}
}

// MockSymlinkFSMockRecorder is the mock recorder for MockSymlinkFS.
type MockSymlinkFSMockRecorder struct {
	mock *MockSymlinkFS
}

// NewMockSymlinkFS creates a new mock instance.
func NewMockSymlinkFS(ctrl *gomock.Controller) *MockSymlinkFS {
	mock := &MockSymlinkFS{ctrl: ctrl}
	mock.recorder = &MockSymlinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSymlinkFS) EXPECT() *MockSymlinkFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockSymlinkFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockSymlinkFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockSymlinkFS)(nil).Open), name)
}

// Symlink mocks base method.
func (m *MockSymlinkFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *MockSymlinkFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*MockSymlinkFS)(nil).Symlink), oldname, newname)
}

// MockTempFileFS is a mock of TempFileFS interface.
type MockTempFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockTempFileFSMockRecorder
	isgomock struct{}
}

// MockTempFileFSMockRecorder is the mock recorder for MockTempFileFS.
type MockTempFileFSMockRecorder struct {
	mock *MockTempFileFS
}

// NewMockTempFileFS creates a new mock instance.
func NewMockTempFileFS(ctrl *gomock.Controller) *MockTempFileFS {
	mock := &MockTempFileFS{ctrl: ctrl}
	mock.recorder = &MockTempFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTempFileFS) EXPECT() *MockTempFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockTempFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockTempFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockTempFileFS)(nil).Open), name)
}

// TempFile mocks base method.
func (m *MockTempFileFS) TempFile(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempFile", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempFile indicates an expected call of TempFile.
func (mr *MockTempFileFSMockRecorder) TempFile(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempFile", reflect.TypeOf((*MockTempFileFS)(nil).TempFile), dir, pattern)
}

// MockWriteFileFS is a mock of WriteFileFS interface.
type MockWriteFileFS struct {
	ctrl     *gomock.Controller
	recorder *MockWriteFileFSMockRecorder
	isgomock struct{}
}

// MockWriteFileFSMockRecorder is the mock recorder for MockWriteFileFS.
type MockWriteFileFSMockRecorder struct {
	mock *MockWriteFileFS
}

// NewMockWriteFileFS creates a new mock instance.
func NewMockWriteFileFS(ctrl *gomock.Controller) *MockWriteFileFS {
	mock := &MockWriteFileFS{ctrl: ctrl}
	mock.recorder = &MockWriteFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteFileFS) EXPECT() *MockWriteFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockWriteFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWriteFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWriteFileFS)(nil).Open), name)
}

// WriteFile mocks base method.
func (m *MockWriteFileFS) WriteFile(name string, data []byte, perm ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockWriteFileFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockWriteFileFS)(nil).WriteFile), name, data, perm)
}
