// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unstoppablemango/ihfs (interfaces: ChmodFS,ChownFS,ChtimesFS,CopyFS,CreateFS,CreateTempFS,GlobFS,LinkerFS,MkdirFS,MkdirAllFS,MkdirTempFS,OpenFileFS,OsFS,ReadDirFS,ReadDirNamesFS,ReadFileFS,ReadLinkFS,RemoveFS,RemoveAllFS,RenameFS,StatFS,SubFS,SymlinkFS,TempFileFS,WriteFileFS)
//
// Generated by this command:
//
//	mockgen -destination=mock_fs.go -package=mockfs -mock_names=ChmodFS=ChmodFS,ChownFS=ChownFS,ChtimesFS=ChtimesFS,CopyFS=CopyFS,CreateFS=CreateFS,CreateTempFS=CreateTempFS,GlobFS=GlobFS,LinkerFS=LinkerFS,MkdirFS=MkdirFS,MkdirAllFS=MkdirAllFS,MkdirTempFS=MkdirTempFS,OpenFileFS=OpenFileFS,OsFS=OsFS,ReadDirFS=ReadDirFS,ReadDirNamesFS=ReadDirNamesFS,ReadFileFS=ReadFileFS,ReadLinkFS=ReadLinkFS,RemoveFS=RemoveFS,RemoveAllFS=RemoveAllFS,RenameFS=RenameFS,StatFS=StatFS,SubFS=SubFS,SymlinkFS=SymlinkFS,TempFileFS=TempFileFS,WriteFileFS=WriteFileFS github.com/unstoppablemango/ihfs ChmodFS,ChownFS,ChtimesFS,CopyFS,CreateFS,CreateTempFS,GlobFS,LinkerFS,MkdirFS,MkdirAllFS,MkdirTempFS,OpenFileFS,OsFS,ReadDirFS,ReadDirNamesFS,ReadFileFS,ReadLinkFS,RemoveFS,RemoveAllFS,RenameFS,StatFS,SubFS,SymlinkFS,TempFileFS,WriteFileFS
//

// Package mockfs is a generated GoMock package.
package mockfs

import (
	fs "io/fs"
	reflect "reflect"
	time "time"

	os "github.com/unmango/go/os"
	ihfs "github.com/unstoppablemango/ihfs"
	gomock "go.uber.org/mock/gomock"
)

// ChmodFS is a mock of ChmodFS interface.
type ChmodFS struct {
	ctrl     *gomock.Controller
	recorder *ChmodFSMockRecorder
	isgomock struct{}
}

// ChmodFSMockRecorder is the mock recorder for ChmodFS.
type ChmodFSMockRecorder struct {
	mock *ChmodFS
}

// NewChmodFS creates a new mock instance.
func NewChmodFS(ctrl *gomock.Controller) *ChmodFS {
	mock := &ChmodFS{ctrl: ctrl}
	mock.recorder = &ChmodFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ChmodFS) EXPECT() *ChmodFSMockRecorder {
	return m.recorder
}

// Chmod mocks base method.
func (m *ChmodFS) Chmod(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *ChmodFSMockRecorder) Chmod(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*ChmodFS)(nil).Chmod), name, mode)
}

// Open mocks base method.
func (m *ChmodFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ChmodFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ChmodFS)(nil).Open), name)
}

// ChownFS is a mock of ChownFS interface.
type ChownFS struct {
	ctrl     *gomock.Controller
	recorder *ChownFSMockRecorder
	isgomock struct{}
}

// ChownFSMockRecorder is the mock recorder for ChownFS.
type ChownFSMockRecorder struct {
	mock *ChownFS
}

// NewChownFS creates a new mock instance.
func NewChownFS(ctrl *gomock.Controller) *ChownFS {
	mock := &ChownFS{ctrl: ctrl}
	mock.recorder = &ChownFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ChownFS) EXPECT() *ChownFSMockRecorder {
	return m.recorder
}

// Chown mocks base method.
func (m *ChownFS) Chown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *ChownFSMockRecorder) Chown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*ChownFS)(nil).Chown), name, uid, gid)
}

// Open mocks base method.
func (m *ChownFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ChownFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ChownFS)(nil).Open), name)
}

// ChtimesFS is a mock of ChtimesFS interface.
type ChtimesFS struct {
	ctrl     *gomock.Controller
	recorder *ChtimesFSMockRecorder
	isgomock struct{}
}

// ChtimesFSMockRecorder is the mock recorder for ChtimesFS.
type ChtimesFSMockRecorder struct {
	mock *ChtimesFS
}

// NewChtimesFS creates a new mock instance.
func NewChtimesFS(ctrl *gomock.Controller) *ChtimesFS {
	mock := &ChtimesFS{ctrl: ctrl}
	mock.recorder = &ChtimesFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ChtimesFS) EXPECT() *ChtimesFSMockRecorder {
	return m.recorder
}

// Chtimes mocks base method.
func (m *ChtimesFS) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *ChtimesFSMockRecorder) Chtimes(name, atime, mtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*ChtimesFS)(nil).Chtimes), name, atime, mtime)
}

// Open mocks base method.
func (m *ChtimesFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ChtimesFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ChtimesFS)(nil).Open), name)
}

// CopyFS is a mock of CopyFS interface.
type CopyFS struct {
	ctrl     *gomock.Controller
	recorder *CopyFSMockRecorder
	isgomock struct{}
}

// CopyFSMockRecorder is the mock recorder for CopyFS.
type CopyFSMockRecorder struct {
	mock *CopyFS
}

// NewCopyFS creates a new mock instance.
func NewCopyFS(ctrl *gomock.Controller) *CopyFS {
	mock := &CopyFS{ctrl: ctrl}
	mock.recorder = &CopyFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CopyFS) EXPECT() *CopyFSMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *CopyFS) Copy(dir string, fsys ihfs.FS) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", dir, fsys)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *CopyFSMockRecorder) Copy(dir, fsys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*CopyFS)(nil).Copy), dir, fsys)
}

// Open mocks base method.
func (m *CopyFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *CopyFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*CopyFS)(nil).Open), name)
}

// CreateFS is a mock of CreateFS interface.
type CreateFS struct {
	ctrl     *gomock.Controller
	recorder *CreateFSMockRecorder
	isgomock struct{}
}

// CreateFSMockRecorder is the mock recorder for CreateFS.
type CreateFSMockRecorder struct {
	mock *CreateFS
}

// NewCreateFS creates a new mock instance.
func NewCreateFS(ctrl *gomock.Controller) *CreateFS {
	mock := &CreateFS{ctrl: ctrl}
	mock.recorder = &CreateFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CreateFS) EXPECT() *CreateFSMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *CreateFS) Create(name string) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *CreateFSMockRecorder) Create(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*CreateFS)(nil).Create), name)
}

// Open mocks base method.
func (m *CreateFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *CreateFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*CreateFS)(nil).Open), name)
}

// CreateTempFS is a mock of CreateTempFS interface.
type CreateTempFS struct {
	ctrl     *gomock.Controller
	recorder *CreateTempFSMockRecorder
	isgomock struct{}
}

// CreateTempFSMockRecorder is the mock recorder for CreateTempFS.
type CreateTempFSMockRecorder struct {
	mock *CreateTempFS
}

// NewCreateTempFS creates a new mock instance.
func NewCreateTempFS(ctrl *gomock.Controller) *CreateTempFS {
	mock := &CreateTempFS{ctrl: ctrl}
	mock.recorder = &CreateTempFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CreateTempFS) EXPECT() *CreateTempFSMockRecorder {
	return m.recorder
}

// CreateTemp mocks base method.
func (m *CreateTempFS) CreateTemp(dir, pattern string) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemp", dir, pattern)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemp indicates an expected call of CreateTemp.
func (mr *CreateTempFSMockRecorder) CreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemp", reflect.TypeOf((*CreateTempFS)(nil).CreateTemp), dir, pattern)
}

// Open mocks base method.
func (m *CreateTempFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *CreateTempFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*CreateTempFS)(nil).Open), name)
}

// GlobFS is a mock of GlobFS interface.
type GlobFS struct {
	ctrl     *gomock.Controller
	recorder *GlobFSMockRecorder
	isgomock struct{}
}

// GlobFSMockRecorder is the mock recorder for GlobFS.
type GlobFSMockRecorder struct {
	mock *GlobFS
}

// NewGlobFS creates a new mock instance.
func NewGlobFS(ctrl *gomock.Controller) *GlobFS {
	mock := &GlobFS{ctrl: ctrl}
	mock.recorder = &GlobFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GlobFS) EXPECT() *GlobFSMockRecorder {
	return m.recorder
}

// Glob mocks base method.
func (m *GlobFS) Glob(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Glob", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Glob indicates an expected call of Glob.
func (mr *GlobFSMockRecorder) Glob(pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Glob", reflect.TypeOf((*GlobFS)(nil).Glob), pattern)
}

// Open mocks base method.
func (m *GlobFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *GlobFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*GlobFS)(nil).Open), name)
}

// LinkerFS is a mock of LinkerFS interface.
type LinkerFS struct {
	ctrl     *gomock.Controller
	recorder *LinkerFSMockRecorder
	isgomock struct{}
}

// LinkerFSMockRecorder is the mock recorder for LinkerFS.
type LinkerFSMockRecorder struct {
	mock *LinkerFS
}

// NewLinkerFS creates a new mock instance.
func NewLinkerFS(ctrl *gomock.Controller) *LinkerFS {
	mock := &LinkerFS{ctrl: ctrl}
	mock.recorder = &LinkerFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *LinkerFS) EXPECT() *LinkerFSMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *LinkerFS) Lstat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *LinkerFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*LinkerFS)(nil).Lstat), name)
}

// Open mocks base method.
func (m *LinkerFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *LinkerFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*LinkerFS)(nil).Open), name)
}

// ReadLink mocks base method.
func (m *LinkerFS) ReadLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *LinkerFSMockRecorder) ReadLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*LinkerFS)(nil).ReadLink), name)
}

// Symlink mocks base method.
func (m *LinkerFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *LinkerFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*LinkerFS)(nil).Symlink), oldname, newname)
}

// MkdirFS is a mock of MkdirFS interface.
type MkdirFS struct {
	ctrl     *gomock.Controller
	recorder *MkdirFSMockRecorder
	isgomock struct{}
}

// MkdirFSMockRecorder is the mock recorder for MkdirFS.
type MkdirFSMockRecorder struct {
	mock *MkdirFS
}

// NewMkdirFS creates a new mock instance.
func NewMkdirFS(ctrl *gomock.Controller) *MkdirFS {
	mock := &MkdirFS{ctrl: ctrl}
	mock.recorder = &MkdirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MkdirFS) EXPECT() *MkdirFSMockRecorder {
	return m.recorder
}

// Mkdir mocks base method.
func (m *MkdirFS) Mkdir(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *MkdirFSMockRecorder) Mkdir(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*MkdirFS)(nil).Mkdir), name, mode)
}

// Open mocks base method.
func (m *MkdirFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MkdirFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MkdirFS)(nil).Open), name)
}

// MkdirAllFS is a mock of MkdirAllFS interface.
type MkdirAllFS struct {
	ctrl     *gomock.Controller
	recorder *MkdirAllFSMockRecorder
	isgomock struct{}
}

// MkdirAllFSMockRecorder is the mock recorder for MkdirAllFS.
type MkdirAllFSMockRecorder struct {
	mock *MkdirAllFS
}

// NewMkdirAllFS creates a new mock instance.
func NewMkdirAllFS(ctrl *gomock.Controller) *MkdirAllFS {
	mock := &MkdirAllFS{ctrl: ctrl}
	mock.recorder = &MkdirAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MkdirAllFS) EXPECT() *MkdirAllFSMockRecorder {
	return m.recorder
}

// MkdirAll mocks base method.
func (m *MkdirAllFS) MkdirAll(name string, mode ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MkdirAllFSMockRecorder) MkdirAll(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MkdirAllFS)(nil).MkdirAll), name, mode)
}

// Open mocks base method.
func (m *MkdirAllFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MkdirAllFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MkdirAllFS)(nil).Open), name)
}

// MkdirTempFS is a mock of MkdirTempFS interface.
type MkdirTempFS struct {
	ctrl     *gomock.Controller
	recorder *MkdirTempFSMockRecorder
	isgomock struct{}
}

// MkdirTempFSMockRecorder is the mock recorder for MkdirTempFS.
type MkdirTempFSMockRecorder struct {
	mock *MkdirTempFS
}

// NewMkdirTempFS creates a new mock instance.
func NewMkdirTempFS(ctrl *gomock.Controller) *MkdirTempFS {
	mock := &MkdirTempFS{ctrl: ctrl}
	mock.recorder = &MkdirTempFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MkdirTempFS) EXPECT() *MkdirTempFSMockRecorder {
	return m.recorder
}

// MkdirTemp mocks base method.
func (m *MkdirTempFS) MkdirTemp(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirTemp", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MkdirTemp indicates an expected call of MkdirTemp.
func (mr *MkdirTempFSMockRecorder) MkdirTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirTemp", reflect.TypeOf((*MkdirTempFS)(nil).MkdirTemp), dir, pattern)
}

// Open mocks base method.
func (m *MkdirTempFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MkdirTempFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MkdirTempFS)(nil).Open), name)
}

// OpenFileFS is a mock of OpenFileFS interface.
type OpenFileFS struct {
	ctrl     *gomock.Controller
	recorder *OpenFileFSMockRecorder
	isgomock struct{}
}

// OpenFileFSMockRecorder is the mock recorder for OpenFileFS.
type OpenFileFSMockRecorder struct {
	mock *OpenFileFS
}

// NewOpenFileFS creates a new mock instance.
func NewOpenFileFS(ctrl *gomock.Controller) *OpenFileFS {
	mock := &OpenFileFS{ctrl: ctrl}
	mock.recorder = &OpenFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OpenFileFS) EXPECT() *OpenFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *OpenFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *OpenFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*OpenFileFS)(nil).Open), name)
}

// OpenFile mocks base method.
func (m *OpenFileFS) OpenFile(name string, flag int, perm ihfs.FileMode) (ihfs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenFile", name, flag, perm)
	ret0, _ := ret[0].(ihfs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenFile indicates an expected call of OpenFile.
func (mr *OpenFileFSMockRecorder) OpenFile(name, flag, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenFile", reflect.TypeOf((*OpenFileFS)(nil).OpenFile), name, flag, perm)
}

// OsFS is a mock of OsFS interface.
type OsFS struct {
	ctrl     *gomock.Controller
	recorder *OsFSMockRecorder
	isgomock struct{}
}

// OsFSMockRecorder is the mock recorder for OsFS.
type OsFSMockRecorder struct {
	mock *OsFS
}

// NewOsFS creates a new mock instance.
func NewOsFS(ctrl *gomock.Controller) *OsFS {
	mock := &OsFS{ctrl: ctrl}
	mock.recorder = &OsFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OsFS) EXPECT() *OsFSMockRecorder {
	return m.recorder
}

// Chdir mocks base method.
func (m *OsFS) Chdir(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chdir", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chdir indicates an expected call of Chdir.
func (mr *OsFSMockRecorder) Chdir(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chdir", reflect.TypeOf((*OsFS)(nil).Chdir), dir)
}

// Chmod mocks base method.
func (m *OsFS) Chmod(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chmod", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chmod indicates an expected call of Chmod.
func (mr *OsFSMockRecorder) Chmod(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chmod", reflect.TypeOf((*OsFS)(nil).Chmod), name, mode)
}

// Chown mocks base method.
func (m *OsFS) Chown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chown indicates an expected call of Chown.
func (mr *OsFSMockRecorder) Chown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chown", reflect.TypeOf((*OsFS)(nil).Chown), name, uid, gid)
}

// Chtimes mocks base method.
func (m *OsFS) Chtimes(name string, atime, mtime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chtimes", name, atime, mtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Chtimes indicates an expected call of Chtimes.
func (mr *OsFSMockRecorder) Chtimes(name, atime, mtime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chtimes", reflect.TypeOf((*OsFS)(nil).Chtimes), name, atime, mtime)
}

// CopyFS mocks base method.
func (m *OsFS) CopyFS(dir string, fsys fs.FS) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFS", dir, fsys)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFS indicates an expected call of CopyFS.
func (mr *OsFSMockRecorder) CopyFS(dir, fsys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFS", reflect.TypeOf((*OsFS)(nil).CopyFS), dir, fsys)
}

// CreateTemp mocks base method.
func (m *OsFS) CreateTemp(dir, pattern string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemp", dir, pattern)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTemp indicates an expected call of CreateTemp.
func (mr *OsFSMockRecorder) CreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemp", reflect.TypeOf((*OsFS)(nil).CreateTemp), dir, pattern)
}

// DirFS mocks base method.
func (m *OsFS) DirFS(dir string) fs.FS {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirFS", dir)
	ret0, _ := ret[0].(fs.FS)
	return ret0
}

// DirFS indicates an expected call of DirFS.
func (mr *OsFSMockRecorder) DirFS(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirFS", reflect.TypeOf((*OsFS)(nil).DirFS), dir)
}

// Lchown mocks base method.
func (m *OsFS) Lchown(name string, uid, gid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lchown", name, uid, gid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lchown indicates an expected call of Lchown.
func (mr *OsFSMockRecorder) Lchown(name, uid, gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lchown", reflect.TypeOf((*OsFS)(nil).Lchown), name, uid, gid)
}

// Link mocks base method.
func (m *OsFS) Link(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Link", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Link indicates an expected call of Link.
func (mr *OsFSMockRecorder) Link(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Link", reflect.TypeOf((*OsFS)(nil).Link), oldname, newname)
}

// Lstat mocks base method.
func (m *OsFS) Lstat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *OsFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*OsFS)(nil).Lstat), name)
}

// Mkdir mocks base method.
func (m *OsFS) Mkdir(name string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mkdir", name, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdir indicates an expected call of Mkdir.
func (mr *OsFSMockRecorder) Mkdir(name, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mkdir", reflect.TypeOf((*OsFS)(nil).Mkdir), name, mode)
}

// MkdirAll mocks base method.
func (m *OsFS) MkdirAll(path string, mode os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *OsFSMockRecorder) MkdirAll(path, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*OsFS)(nil).MkdirAll), path, mode)
}

// MkdirTemp mocks base method.
func (m *OsFS) MkdirTemp(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirTemp", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MkdirTemp indicates an expected call of MkdirTemp.
func (mr *OsFSMockRecorder) MkdirTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirTemp", reflect.TypeOf((*OsFS)(nil).MkdirTemp), dir, pattern)
}

// Open mocks base method.
func (m *OsFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *OsFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*OsFS)(nil).Open), name)
}

// OpenInRoot mocks base method.
func (m *OsFS) OpenInRoot(dir, name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenInRoot", dir, name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenInRoot indicates an expected call of OpenInRoot.
func (mr *OsFSMockRecorder) OpenInRoot(dir, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenInRoot", reflect.TypeOf((*OsFS)(nil).OpenInRoot), dir, name)
}

// OpenRoot mocks base method.
func (m *OsFS) OpenRoot(name string) (*os.Root, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenRoot", name)
	ret0, _ := ret[0].(*os.Root)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenRoot indicates an expected call of OpenRoot.
func (mr *OsFSMockRecorder) OpenRoot(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenRoot", reflect.TypeOf((*OsFS)(nil).OpenRoot), name)
}

// ReadDir mocks base method.
func (m *OsFS) ReadDir(name string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *OsFSMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*OsFS)(nil).ReadDir), name)
}

// ReadFile mocks base method.
func (m *OsFS) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *OsFSMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*OsFS)(nil).ReadFile), name)
}

// Readlink mocks base method.
func (m *OsFS) Readlink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readlink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readlink indicates an expected call of Readlink.
func (mr *OsFSMockRecorder) Readlink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readlink", reflect.TypeOf((*OsFS)(nil).Readlink), name)
}

// Remove mocks base method.
func (m *OsFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *OsFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*OsFS)(nil).Remove), name)
}

// RemoveAll mocks base method.
func (m *OsFS) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *OsFSMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*OsFS)(nil).RemoveAll), path)
}

// Rename mocks base method.
func (m *OsFS) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *OsFSMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*OsFS)(nil).Rename), oldpath, newpath)
}

// SameFile mocks base method.
func (m *OsFS) SameFile(fi1, fi2 os.FileInfo) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameFile", fi1, fi2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameFile indicates an expected call of SameFile.
func (mr *OsFSMockRecorder) SameFile(fi1, fi2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameFile", reflect.TypeOf((*OsFS)(nil).SameFile), fi1, fi2)
}

// Stat mocks base method.
func (m *OsFS) Stat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *OsFSMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*OsFS)(nil).Stat), name)
}

// Symlink mocks base method.
func (m *OsFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *OsFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*OsFS)(nil).Symlink), oldname, newname)
}

// Truncate mocks base method.
func (m *OsFS) Truncate(name string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", name, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *OsFSMockRecorder) Truncate(name, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*OsFS)(nil).Truncate), name, size)
}

// WriteFile mocks base method.
func (m *OsFS) WriteFile(name string, data []byte, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *OsFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*OsFS)(nil).WriteFile), name, data, perm)
}

// ReadDirFS is a mock of ReadDirFS interface.
type ReadDirFS struct {
	ctrl     *gomock.Controller
	recorder *ReadDirFSMockRecorder
	isgomock struct{}
}

// ReadDirFSMockRecorder is the mock recorder for ReadDirFS.
type ReadDirFSMockRecorder struct {
	mock *ReadDirFS
}

// NewReadDirFS creates a new mock instance.
func NewReadDirFS(ctrl *gomock.Controller) *ReadDirFS {
	mock := &ReadDirFS{ctrl: ctrl}
	mock.recorder = &ReadDirFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReadDirFS) EXPECT() *ReadDirFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *ReadDirFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ReadDirFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ReadDirFS)(nil).Open), name)
}

// ReadDir mocks base method.
func (m *ReadDirFS) ReadDir(name string) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", name)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *ReadDirFSMockRecorder) ReadDir(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*ReadDirFS)(nil).ReadDir), name)
}

// ReadDirNamesFS is a mock of ReadDirNamesFS interface.
type ReadDirNamesFS struct {
	ctrl     *gomock.Controller
	recorder *ReadDirNamesFSMockRecorder
	isgomock struct{}
}

// ReadDirNamesFSMockRecorder is the mock recorder for ReadDirNamesFS.
type ReadDirNamesFSMockRecorder struct {
	mock *ReadDirNamesFS
}

// NewReadDirNamesFS creates a new mock instance.
func NewReadDirNamesFS(ctrl *gomock.Controller) *ReadDirNamesFS {
	mock := &ReadDirNamesFS{ctrl: ctrl}
	mock.recorder = &ReadDirNamesFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReadDirNamesFS) EXPECT() *ReadDirNamesFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *ReadDirNamesFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ReadDirNamesFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ReadDirNamesFS)(nil).Open), name)
}

// ReadDirNames mocks base method.
func (m *ReadDirNamesFS) ReadDirNames(name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDirNames", name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDirNames indicates an expected call of ReadDirNames.
func (mr *ReadDirNamesFSMockRecorder) ReadDirNames(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDirNames", reflect.TypeOf((*ReadDirNamesFS)(nil).ReadDirNames), name)
}

// ReadFileFS is a mock of ReadFileFS interface.
type ReadFileFS struct {
	ctrl     *gomock.Controller
	recorder *ReadFileFSMockRecorder
	isgomock struct{}
}

// ReadFileFSMockRecorder is the mock recorder for ReadFileFS.
type ReadFileFSMockRecorder struct {
	mock *ReadFileFS
}

// NewReadFileFS creates a new mock instance.
func NewReadFileFS(ctrl *gomock.Controller) *ReadFileFS {
	mock := &ReadFileFS{ctrl: ctrl}
	mock.recorder = &ReadFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReadFileFS) EXPECT() *ReadFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *ReadFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ReadFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ReadFileFS)(nil).Open), name)
}

// ReadFile mocks base method.
func (m *ReadFileFS) ReadFile(name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *ReadFileFSMockRecorder) ReadFile(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*ReadFileFS)(nil).ReadFile), name)
}

// ReadLinkFS is a mock of ReadLinkFS interface.
type ReadLinkFS struct {
	ctrl     *gomock.Controller
	recorder *ReadLinkFSMockRecorder
	isgomock struct{}
}

// ReadLinkFSMockRecorder is the mock recorder for ReadLinkFS.
type ReadLinkFSMockRecorder struct {
	mock *ReadLinkFS
}

// NewReadLinkFS creates a new mock instance.
func NewReadLinkFS(ctrl *gomock.Controller) *ReadLinkFS {
	mock := &ReadLinkFS{ctrl: ctrl}
	mock.recorder = &ReadLinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReadLinkFS) EXPECT() *ReadLinkFSMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *ReadLinkFS) Lstat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *ReadLinkFSMockRecorder) Lstat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*ReadLinkFS)(nil).Lstat), name)
}

// Open mocks base method.
func (m *ReadLinkFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *ReadLinkFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*ReadLinkFS)(nil).Open), name)
}

// ReadLink mocks base method.
func (m *ReadLinkFS) ReadLink(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLink", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLink indicates an expected call of ReadLink.
func (mr *ReadLinkFSMockRecorder) ReadLink(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLink", reflect.TypeOf((*ReadLinkFS)(nil).ReadLink), name)
}

// RemoveFS is a mock of RemoveFS interface.
type RemoveFS struct {
	ctrl     *gomock.Controller
	recorder *RemoveFSMockRecorder
	isgomock struct{}
}

// RemoveFSMockRecorder is the mock recorder for RemoveFS.
type RemoveFSMockRecorder struct {
	mock *RemoveFS
}

// NewRemoveFS creates a new mock instance.
func NewRemoveFS(ctrl *gomock.Controller) *RemoveFS {
	mock := &RemoveFS{ctrl: ctrl}
	mock.recorder = &RemoveFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RemoveFS) EXPECT() *RemoveFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *RemoveFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *RemoveFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*RemoveFS)(nil).Open), name)
}

// Remove mocks base method.
func (m *RemoveFS) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *RemoveFSMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*RemoveFS)(nil).Remove), name)
}

// RemoveAllFS is a mock of RemoveAllFS interface.
type RemoveAllFS struct {
	ctrl     *gomock.Controller
	recorder *RemoveAllFSMockRecorder
	isgomock struct{}
}

// RemoveAllFSMockRecorder is the mock recorder for RemoveAllFS.
type RemoveAllFSMockRecorder struct {
	mock *RemoveAllFS
}

// NewRemoveAllFS creates a new mock instance.
func NewRemoveAllFS(ctrl *gomock.Controller) *RemoveAllFS {
	mock := &RemoveAllFS{ctrl: ctrl}
	mock.recorder = &RemoveAllFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RemoveAllFS) EXPECT() *RemoveAllFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *RemoveAllFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *RemoveAllFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*RemoveAllFS)(nil).Open), name)
}

// RemoveAll mocks base method.
func (m *RemoveAllFS) RemoveAll(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *RemoveAllFSMockRecorder) RemoveAll(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*RemoveAllFS)(nil).RemoveAll), name)
}

// RenameFS is a mock of RenameFS interface.
type RenameFS struct {
	ctrl     *gomock.Controller
	recorder *RenameFSMockRecorder
	isgomock struct{}
}

// RenameFSMockRecorder is the mock recorder for RenameFS.
type RenameFSMockRecorder struct {
	mock *RenameFS
}

// NewRenameFS creates a new mock instance.
func NewRenameFS(ctrl *gomock.Controller) *RenameFS {
	mock := &RenameFS{ctrl: ctrl}
	mock.recorder = &RenameFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RenameFS) EXPECT() *RenameFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *RenameFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *RenameFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*RenameFS)(nil).Open), name)
}

// Rename mocks base method.
func (m *RenameFS) Rename(oldpath, newpath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", oldpath, newpath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename.
func (mr *RenameFSMockRecorder) Rename(oldpath, newpath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*RenameFS)(nil).Rename), oldpath, newpath)
}

// StatFS is a mock of StatFS interface.
type StatFS struct {
	ctrl     *gomock.Controller
	recorder *StatFSMockRecorder
	isgomock struct{}
}

// StatFSMockRecorder is the mock recorder for StatFS.
type StatFSMockRecorder struct {
	mock *StatFS
}

// NewStatFS creates a new mock instance.
func NewStatFS(ctrl *gomock.Controller) *StatFS {
	mock := &StatFS{ctrl: ctrl}
	mock.recorder = &StatFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StatFS) EXPECT() *StatFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *StatFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *StatFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*StatFS)(nil).Open), name)
}

// Stat mocks base method.
func (m *StatFS) Stat(name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *StatFSMockRecorder) Stat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*StatFS)(nil).Stat), name)
}

// SubFS is a mock of SubFS interface.
type SubFS struct {
	ctrl     *gomock.Controller
	recorder *SubFSMockRecorder
	isgomock struct{}
}

// SubFSMockRecorder is the mock recorder for SubFS.
type SubFSMockRecorder struct {
	mock *SubFS
}

// NewSubFS creates a new mock instance.
func NewSubFS(ctrl *gomock.Controller) *SubFS {
	mock := &SubFS{ctrl: ctrl}
	mock.recorder = &SubFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SubFS) EXPECT() *SubFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *SubFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *SubFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*SubFS)(nil).Open), name)
}

// Sub mocks base method.
func (m *SubFS) Sub(dir string) (fs.FS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sub", dir)
	ret0, _ := ret[0].(fs.FS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sub indicates an expected call of Sub.
func (mr *SubFSMockRecorder) Sub(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sub", reflect.TypeOf((*SubFS)(nil).Sub), dir)
}

// SymlinkFS is a mock of SymlinkFS interface.
type SymlinkFS struct {
	ctrl     *gomock.Controller
	recorder *SymlinkFSMockRecorder
	isgomock struct{}
}

// SymlinkFSMockRecorder is the mock recorder for SymlinkFS.
type SymlinkFSMockRecorder struct {
	mock *SymlinkFS
}

// NewSymlinkFS creates a new mock instance.
func NewSymlinkFS(ctrl *gomock.Controller) *SymlinkFS {
	mock := &SymlinkFS{ctrl: ctrl}
	mock.recorder = &SymlinkFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SymlinkFS) EXPECT() *SymlinkFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *SymlinkFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *SymlinkFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*SymlinkFS)(nil).Open), name)
}

// Symlink mocks base method.
func (m *SymlinkFS) Symlink(oldname, newname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Symlink", oldname, newname)
	ret0, _ := ret[0].(error)
	return ret0
}

// Symlink indicates an expected call of Symlink.
func (mr *SymlinkFSMockRecorder) Symlink(oldname, newname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Symlink", reflect.TypeOf((*SymlinkFS)(nil).Symlink), oldname, newname)
}

// TempFileFS is a mock of TempFileFS interface.
type TempFileFS struct {
	ctrl     *gomock.Controller
	recorder *TempFileFSMockRecorder
	isgomock struct{}
}

// TempFileFSMockRecorder is the mock recorder for TempFileFS.
type TempFileFSMockRecorder struct {
	mock *TempFileFS
}

// NewTempFileFS creates a new mock instance.
func NewTempFileFS(ctrl *gomock.Controller) *TempFileFS {
	mock := &TempFileFS{ctrl: ctrl}
	mock.recorder = &TempFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TempFileFS) EXPECT() *TempFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *TempFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *TempFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*TempFileFS)(nil).Open), name)
}

// TempFile mocks base method.
func (m *TempFileFS) TempFile(dir, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TempFile", dir, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TempFile indicates an expected call of TempFile.
func (mr *TempFileFSMockRecorder) TempFile(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TempFile", reflect.TypeOf((*TempFileFS)(nil).TempFile), dir, pattern)
}

// WriteFileFS is a mock of WriteFileFS interface.
type WriteFileFS struct {
	ctrl     *gomock.Controller
	recorder *WriteFileFSMockRecorder
	isgomock struct{}
}

// WriteFileFSMockRecorder is the mock recorder for WriteFileFS.
type WriteFileFSMockRecorder struct {
	mock *WriteFileFS
}

// NewWriteFileFS creates a new mock instance.
func NewWriteFileFS(ctrl *gomock.Controller) *WriteFileFS {
	mock := &WriteFileFS{ctrl: ctrl}
	mock.recorder = &WriteFileFSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WriteFileFS) EXPECT() *WriteFileFSMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *WriteFileFS) Open(name string) (fs.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", name)
	ret0, _ := ret[0].(fs.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *WriteFileFSMockRecorder) Open(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*WriteFileFS)(nil).Open), name)
}

// WriteFile mocks base method.
func (m *WriteFileFS) WriteFile(name string, data []byte, perm ihfs.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", name, data, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *WriteFileFSMockRecorder) WriteFile(name, data, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*WriteFileFS)(nil).WriteFile), name, data, perm)
}
