// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/unstoppablemango/ihfs (interfaces: DirNameReader,DirReader,File,Operation,ReaderAt,ReadDirFile,Seeker,StringWriter,Syncer,Truncater,Writer,WriterAt)
//
// Generated by this command:
//
//	mockgen -destination=mock_file.go -package=mockfs -mock_names=DirNameReader=DirNameReader,DirReader=DirReader,File=File,Operation=Operation,ReaderAt=ReaderAt,ReadDirFile=ReadDirFile,Seeker=Seeker,StringWriter=StringWriter,Syncer=Syncer,Truncater=Truncater,Writer=Writer,WriterAt=WriterAt github.com/unstoppablemango/ihfs DirNameReader,DirReader,File,Operation,ReaderAt,ReadDirFile,Seeker,StringWriter,Syncer,Truncater,Writer,WriterAt
//

// Package mockfs is a generated GoMock package.
package mockfs

import (
	fs "io/fs"
	reflect "reflect"

	ihfs "github.com/unstoppablemango/ihfs"
	gomock "go.uber.org/mock/gomock"
)

// DirNameReader is a mock of DirNameReader interface.
type DirNameReader struct {
	ctrl     *gomock.Controller
	recorder *DirNameReaderMockRecorder
	isgomock struct{}
}

// DirNameReaderMockRecorder is the mock recorder for DirNameReader.
type DirNameReaderMockRecorder struct {
	mock *DirNameReader
}

// NewDirNameReader creates a new mock instance.
func NewDirNameReader(ctrl *gomock.Controller) *DirNameReader {
	mock := &DirNameReader{ctrl: ctrl}
	mock.recorder = &DirNameReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DirNameReader) EXPECT() *DirNameReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *DirNameReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *DirNameReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*DirNameReader)(nil).Close))
}

// Read mocks base method.
func (m *DirNameReader) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *DirNameReaderMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*DirNameReader)(nil).Read), arg0)
}

// ReadDirNames mocks base method.
func (m *DirNameReader) ReadDirNames(n int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDirNames", n)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDirNames indicates an expected call of ReadDirNames.
func (mr *DirNameReaderMockRecorder) ReadDirNames(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDirNames", reflect.TypeOf((*DirNameReader)(nil).ReadDirNames), n)
}

// Stat mocks base method.
func (m *DirNameReader) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *DirNameReaderMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*DirNameReader)(nil).Stat))
}

// DirReader is a mock of DirReader interface.
type DirReader struct {
	ctrl     *gomock.Controller
	recorder *DirReaderMockRecorder
	isgomock struct{}
}

// DirReaderMockRecorder is the mock recorder for DirReader.
type DirReaderMockRecorder struct {
	mock *DirReader
}

// NewDirReader creates a new mock instance.
func NewDirReader(ctrl *gomock.Controller) *DirReader {
	mock := &DirReader{ctrl: ctrl}
	mock.recorder = &DirReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DirReader) EXPECT() *DirReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *DirReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *DirReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*DirReader)(nil).Close))
}

// Read mocks base method.
func (m *DirReader) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *DirReaderMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*DirReader)(nil).Read), arg0)
}

// ReadDir mocks base method.
func (m *DirReader) ReadDir(n int) ([]ihfs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", n)
	ret0, _ := ret[0].([]ihfs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *DirReaderMockRecorder) ReadDir(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*DirReader)(nil).ReadDir), n)
}

// Stat mocks base method.
func (m *DirReader) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *DirReaderMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*DirReader)(nil).Stat))
}

// File is a mock of File interface.
type File struct {
	ctrl     *gomock.Controller
	recorder *FileMockRecorder
	isgomock struct{}
}

// FileMockRecorder is the mock recorder for File.
type FileMockRecorder struct {
	mock *File
}

// NewFile creates a new mock instance.
func NewFile(ctrl *gomock.Controller) *File {
	mock := &File{ctrl: ctrl}
	mock.recorder = &FileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *File) EXPECT() *FileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *File) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *FileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*File)(nil).Close))
}

// Read mocks base method.
func (m *File) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *FileMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*File)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *File) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *FileMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*File)(nil).Stat))
}

// Operation is a mock of Operation interface.
type Operation struct {
	ctrl     *gomock.Controller
	recorder *OperationMockRecorder
	isgomock struct{}
}

// OperationMockRecorder is the mock recorder for Operation.
type OperationMockRecorder struct {
	mock *Operation
}

// NewOperation creates a new mock instance.
func NewOperation(ctrl *gomock.Controller) *Operation {
	mock := &Operation{ctrl: ctrl}
	mock.recorder = &OperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Operation) EXPECT() *OperationMockRecorder {
	return m.recorder
}

// Subject mocks base method.
func (m *Operation) Subject() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subject")
	ret0, _ := ret[0].(string)
	return ret0
}

// Subject indicates an expected call of Subject.
func (mr *OperationMockRecorder) Subject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subject", reflect.TypeOf((*Operation)(nil).Subject))
}

// ReaderAt is a mock of ReaderAt interface.
type ReaderAt struct {
	ctrl     *gomock.Controller
	recorder *ReaderAtMockRecorder
	isgomock struct{}
}

// ReaderAtMockRecorder is the mock recorder for ReaderAt.
type ReaderAtMockRecorder struct {
	mock *ReaderAt
}

// NewReaderAt creates a new mock instance.
func NewReaderAt(ctrl *gomock.Controller) *ReaderAt {
	mock := &ReaderAt{ctrl: ctrl}
	mock.recorder = &ReaderAtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReaderAt) EXPECT() *ReaderAtMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *ReaderAt) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *ReaderAtMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*ReaderAt)(nil).Close))
}

// Read mocks base method.
func (m *ReaderAt) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *ReaderAtMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*ReaderAt)(nil).Read), arg0)
}

// ReadAt mocks base method.
func (m *ReaderAt) ReadAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *ReaderAtMockRecorder) ReadAt(p, off any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*ReaderAt)(nil).ReadAt), p, off)
}

// Stat mocks base method.
func (m *ReaderAt) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *ReaderAtMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*ReaderAt)(nil).Stat))
}

// ReadDirFile is a mock of ReadDirFile interface.
type ReadDirFile struct {
	ctrl     *gomock.Controller
	recorder *ReadDirFileMockRecorder
	isgomock struct{}
}

// ReadDirFileMockRecorder is the mock recorder for ReadDirFile.
type ReadDirFileMockRecorder struct {
	mock *ReadDirFile
}

// NewReadDirFile creates a new mock instance.
func NewReadDirFile(ctrl *gomock.Controller) *ReadDirFile {
	mock := &ReadDirFile{ctrl: ctrl}
	mock.recorder = &ReadDirFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ReadDirFile) EXPECT() *ReadDirFileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *ReadDirFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *ReadDirFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*ReadDirFile)(nil).Close))
}

// Read mocks base method.
func (m *ReadDirFile) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *ReadDirFileMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*ReadDirFile)(nil).Read), arg0)
}

// ReadDir mocks base method.
func (m *ReadDirFile) ReadDir(n int) ([]fs.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", n)
	ret0, _ := ret[0].([]fs.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *ReadDirFileMockRecorder) ReadDir(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*ReadDirFile)(nil).ReadDir), n)
}

// Stat mocks base method.
func (m *ReadDirFile) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *ReadDirFileMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*ReadDirFile)(nil).Stat))
}

// Seeker is a mock of Seeker interface.
type Seeker struct {
	ctrl     *gomock.Controller
	recorder *SeekerMockRecorder
	isgomock struct{}
}

// SeekerMockRecorder is the mock recorder for Seeker.
type SeekerMockRecorder struct {
	mock *Seeker
}

// NewSeeker creates a new mock instance.
func NewSeeker(ctrl *gomock.Controller) *Seeker {
	mock := &Seeker{ctrl: ctrl}
	mock.recorder = &SeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Seeker) EXPECT() *SeekerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Seeker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *SeekerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Seeker)(nil).Close))
}

// Read mocks base method.
func (m *Seeker) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *SeekerMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Seeker)(nil).Read), arg0)
}

// Seek mocks base method.
func (m *Seeker) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *SeekerMockRecorder) Seek(offset, whence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*Seeker)(nil).Seek), offset, whence)
}

// Stat mocks base method.
func (m *Seeker) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *SeekerMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*Seeker)(nil).Stat))
}

// StringWriter is a mock of StringWriter interface.
type StringWriter struct {
	ctrl     *gomock.Controller
	recorder *StringWriterMockRecorder
	isgomock struct{}
}

// StringWriterMockRecorder is the mock recorder for StringWriter.
type StringWriterMockRecorder struct {
	mock *StringWriter
}

// NewStringWriter creates a new mock instance.
func NewStringWriter(ctrl *gomock.Controller) *StringWriter {
	mock := &StringWriter{ctrl: ctrl}
	mock.recorder = &StringWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StringWriter) EXPECT() *StringWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *StringWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *StringWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*StringWriter)(nil).Close))
}

// Read mocks base method.
func (m *StringWriter) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *StringWriterMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*StringWriter)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *StringWriter) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *StringWriterMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*StringWriter)(nil).Stat))
}

// WriteString mocks base method.
func (m *StringWriter) WriteString(s string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteString", s)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteString indicates an expected call of WriteString.
func (mr *StringWriterMockRecorder) WriteString(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteString", reflect.TypeOf((*StringWriter)(nil).WriteString), s)
}

// Syncer is a mock of Syncer interface.
type Syncer struct {
	ctrl     *gomock.Controller
	recorder *SyncerMockRecorder
	isgomock struct{}
}

// SyncerMockRecorder is the mock recorder for Syncer.
type SyncerMockRecorder struct {
	mock *Syncer
}

// NewSyncer creates a new mock instance.
func NewSyncer(ctrl *gomock.Controller) *Syncer {
	mock := &Syncer{ctrl: ctrl}
	mock.recorder = &SyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Syncer) EXPECT() *SyncerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Syncer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *SyncerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Syncer)(nil).Close))
}

// Read mocks base method.
func (m *Syncer) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *SyncerMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Syncer)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *Syncer) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *SyncerMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*Syncer)(nil).Stat))
}

// Sync mocks base method.
func (m *Syncer) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *SyncerMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*Syncer)(nil).Sync))
}

// Truncater is a mock of Truncater interface.
type Truncater struct {
	ctrl     *gomock.Controller
	recorder *TruncaterMockRecorder
	isgomock struct{}
}

// TruncaterMockRecorder is the mock recorder for Truncater.
type TruncaterMockRecorder struct {
	mock *Truncater
}

// NewTruncater creates a new mock instance.
func NewTruncater(ctrl *gomock.Controller) *Truncater {
	mock := &Truncater{ctrl: ctrl}
	mock.recorder = &TruncaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Truncater) EXPECT() *TruncaterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Truncater) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *TruncaterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Truncater)(nil).Close))
}

// Read mocks base method.
func (m *Truncater) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *TruncaterMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Truncater)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *Truncater) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *TruncaterMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*Truncater)(nil).Stat))
}

// Truncate mocks base method.
func (m *Truncater) Truncate(size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Truncate", size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Truncate indicates an expected call of Truncate.
func (mr *TruncaterMockRecorder) Truncate(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Truncate", reflect.TypeOf((*Truncater)(nil).Truncate), size)
}

// Writer is a mock of Writer interface.
type Writer struct {
	ctrl     *gomock.Controller
	recorder *WriterMockRecorder
	isgomock struct{}
}

// WriterMockRecorder is the mock recorder for Writer.
type WriterMockRecorder struct {
	mock *Writer
}

// NewWriter creates a new mock instance.
func NewWriter(ctrl *gomock.Controller) *Writer {
	mock := &Writer{ctrl: ctrl}
	mock.recorder = &WriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Writer) EXPECT() *WriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Writer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *WriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Writer)(nil).Close))
}

// Read mocks base method.
func (m *Writer) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *WriterMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*Writer)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *Writer) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *WriterMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*Writer)(nil).Stat))
}

// Write mocks base method.
func (m *Writer) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *WriterMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*Writer)(nil).Write), p)
}

// WriterAt is a mock of WriterAt interface.
type WriterAt struct {
	ctrl     *gomock.Controller
	recorder *WriterAtMockRecorder
	isgomock struct{}
}

// WriterAtMockRecorder is the mock recorder for WriterAt.
type WriterAtMockRecorder struct {
	mock *WriterAt
}

// NewWriterAt creates a new mock instance.
func NewWriterAt(ctrl *gomock.Controller) *WriterAt {
	mock := &WriterAt{ctrl: ctrl}
	mock.recorder = &WriterAtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WriterAt) EXPECT() *WriterAtMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *WriterAt) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *WriterAtMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*WriterAt)(nil).Close))
}

// Read mocks base method.
func (m *WriterAt) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *WriterAtMockRecorder) Read(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*WriterAt)(nil).Read), arg0)
}

// Stat mocks base method.
func (m *WriterAt) Stat() (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat")
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *WriterAtMockRecorder) Stat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*WriterAt)(nil).Stat))
}

// WriteAt mocks base method.
func (m *WriterAt) WriteAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAt indicates an expected call of WriteAt.
func (mr *WriterAtMockRecorder) WriteAt(p, off any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAt", reflect.TypeOf((*WriterAt)(nil).WriteAt), p, off)
}
