name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix develop -c make coverprofile.out
        env:
          TEST_ARGS: --skip-package=ctrfs,ghfs,mockfs

      - uses: codecov/codecov-action@v5.5.2
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: coverprofile.out
          flags: core

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - uses: golangci/golangci-lint-action@v9.2.0
        with:
          version-file: .golangci-lint-version

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix develop -c make gomod2nix
      - run: nix develop -c make generate
      - run: git diff --exit-code
