name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go build -v ./...

      - run: >
          go tool ginkgo -r
          --github-output
          --race
          --trace
          --randomize-all
          --coverprofile=cover.out
          --skip-package=ctrfs,ghfs,mockfs

      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: cover.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - uses: golangci/golangci-lint-action@v9.2.0
        with:
          version-file: .golangci-lint-version

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: cachix/install-nix-action@v31.10.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix flake check
      - run: nix build .# .#ctrfs .#ghfs .#mockfs

  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - run: go tool gomod2nix generate
      - run: git diff --exit-code gomod2nix.toml

      - run: go -C ctrfs tool gomod2nix generate
      - run: git diff --exit-code ctrfs/gomod2nix.toml

      - run: go -C ghfs tool gomod2nix generate
      - run: git diff --exit-code ghfs/gomod2nix.toml

      - run: go -C mockfs tool gomod2nix generate
      - run: git diff --exit-code mockfs/gomod2nix.toml

      - run: make generate
      - run: git diff --exit-code

  ctrfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: ctrfs/go.mod
          cache-dependency-path: ctrfs/go.sum

      - run: go -C ctrfs build -v ./...

      - run: >
          go -C ctrfs tool ginkgo -r
          --github-output
          --race
          --trace
          --randomize-all
          --coverprofile=cover.out

      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: ctrfs/cover.out

  ghfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: ghfs/go.mod
          cache-dependency-path: ghfs/go.sum

      - run: go -C ghfs build -v ./...

      - run: >
          go -C ghfs tool ginkgo -r
          --github-output
          --race
          --trace
          --randomize-all
          --coverprofile=cover.out

      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          fail_ci_if_error: true
          files: ghfs/cover.out

  mockfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: mockfs/go.mod
          cache-dependency-path: mockfs/go.sum

      - run: go -C mockfs build -v ./...
