name: mockfs

on:
  push:
    branches: [main]
    paths: [mockfs/**]
  pull_request:
    branches: [main]
    paths:
      - mockfs/**
      - .github/workflows/mockfs.yml
      - flake.nix
      - flake.lock
      - go.mk

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: unmango/actions/setup-nix@56abf92ca6c8e241831118a76b7b2ce1d3b8d414 # v1.1.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix develop -c go -C mockfs build -v ./...
