name: mockfs

on:
  push:
    branches: [main]
    paths: [mockfs/**]
  pull_request:
    branches: [main]
    paths:
      - mockfs/**
      - .github/workflows/mockfs.yml
      - flake.nix
      - flake.lock
      - go.mk

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix develop -c go -C mockfs build -v ./...
