name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  ihfs:
    name: Release ihfs
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - uses: goreleaser/goreleaser-action@v7.0.0
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
